version: "3.9"

services:
  database:
    image: postgres
    container_name: ohmycash-db
    restart: always
    ports: 
      - 5433:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ohmycash
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ohmycash-api
    restart: always
    env_file: .env
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata: